repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix,lf]
