repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix,lf]
    - repo: https://github.com/pre-commit/mirrors-clang-format
      rev: 'v14.0.6'
      hooks:
          - id: clang-format
            args: [--style=file]
            types: ['c', 'c++', 'cuda']
    - repo: https://github.com/kynan/nbstripout
      rev: 0.6.1
      hooks:
        - id: nbstripout
          args: ["--extra-keys='metadata.language_info.version metadata.toc'"]
          types: [jupyter]
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.0.285
      hooks:
        - id: ruff
          args: [ --fix, --exit-non-zero-on-fix ]
