repos:
    - repo: https://github.com/psf/black
      rev: 22.6.0
      hooks:
          - id: black
            exclude: ^(docs)
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
          - id: isort
            types: [file, python]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending
            args: [--fix,lf]
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: 'v0.971'
      hooks:
          - id: mypy
    - repo: local
      hooks:
          - id: pylint
            name: pylint
            entry: poetry run pylint
            language: system
            exclude: ^(docs/|tests/|benchmarks/)
            types: [file, python]
