name: Build Docs
on:
    push:
        branches:
            - main
            - 'docs/**'

jobs:
    build:
        name: Deploy docs
        runs-on: ubuntu-latest
        steps:
          - name: Checkout main
            uses: actions/checkout@v2
          - name: Install poetry
            run: pipx install poetry==1.6.1
          - name: Setup Python
            uses: actions/setup-python@v4
            with:
              python-version: '3.9'
              cache: 'poetry'
          - name: Install mkdocs
            run: poetry install --with extras
          - name: Build Docs
            run: poetry run mkdocs build
          - name: Deploy docs
            uses: peaceiris/actions-gh-pages@v3
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: ./site
